import { access, lstat, readFile, rm } from "node:fs/promises";
import { constants } from "node:fs";
import { resolve, dirname } from "node:path";
import { spawn } from "node:child_process";

const projectRoot = process.cwd();
const artifactNames = [".output", ".wrangler", "dist"];

for (const artifactName of artifactNames) {
  const artifactPath = resolve(projectRoot, artifactName);
  if (dirname(artifactPath) !== projectRoot) {
    throw new Error(`Refusing to clean build artifact outside project root: ${artifactPath}`);
  }

  try {
    const artifact = await lstat(artifactPath);
    if (artifact.isSymbolicLink()) {
      throw new Error(`Refusing to recursively clean symbolic-link build artifact: ${artifactPath}`);
    }
    await rm(artifactPath, { recursive: true, force: false });
    console.log(`[vps-build] Removed previous ${artifactName} artifact.`);
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
}

const viteCli = resolve(projectRoot, "node_modules", "vite", "bin", "vite.js");
await access(viteCli, constants.R_OK);

const viteExitCode = await new Promise((resolveExitCode, reject) => {
  const child = spawn(process.execPath, [viteCli, "build"], {
    cwd: projectRoot,
    env: { ...process.env, FIDELIZE_VPS_BUILD: "1" },
    stdio: "inherit",
  });
  child.once("error", reject);
  child.once("exit", (code, signal) => {
    if (signal) reject(new Error(`Vite build terminated by signal ${signal}`));
    else resolveExitCode(code ?? 1);
  });
});

if (viteExitCode !== 0) throw new Error(`Vite build failed with exit code ${viteExitCode}`);

const requiredNodeEntry = resolve(projectRoot, ".output", "server", "index.mjs");
const publicDirectory = resolve(projectRoot, ".output", "public");
const serviceWorkerPath = resolve(publicDirectory, "sw.js");
const pushWorkerPath = resolve(publicDirectory, "sw-push.js");
const forbiddenWranglerFiles = [
  resolve(projectRoot, ".output", "server", "wrangler.json"),
  resolve(projectRoot, ".wrangler", "deploy", "config.json"),
];

await access(requiredNodeEntry, constants.R_OK);
for (const forbiddenPath of forbiddenWranglerFiles) {
  try {
    await access(forbiddenPath, constants.F_OK);
    throw new Error(`Cloudflare artifact generated by VPS build: ${forbiddenPath}`);
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
}

await access(serviceWorkerPath, constants.R_OK);
await access(pushWorkerPath, constants.R_OK);

const serviceWorkerSource = await readFile(serviceWorkerPath, "utf8");
const workboxReference = serviceWorkerSource.match(/["']\.\/(workbox-[A-Za-z0-9_-]+(?:\.js)?)["']/)?.[1];
if (!workboxReference) {
  throw new Error(`No relative workbox-*.js reference found in ${serviceWorkerPath}`);
}

const workboxFilename = workboxReference.endsWith(".js") ? workboxReference : `${workboxReference}.js`;
const workboxPath = resolve(publicDirectory, workboxFilename);
if (dirname(workboxPath) !== publicDirectory) {
  throw new Error(`Invalid Workbox path referenced by service worker: ${workboxReference}`);
}
await access(workboxPath, constants.R_OK);

if (!serviceWorkerSource.includes('importScripts("/sw-push.js")') && !serviceWorkerSource.includes("importScripts('/sw-push.js')")) {
  throw new Error(`Service worker does not import /sw-push.js: ${serviceWorkerPath}`);
}

console.log(`[vps-build] Node entry confirmed: ${requiredNodeEntry}`);
console.log("[vps-build] Wrangler/Cloudflare deploy configuration absent.");
console.log(`[vps-build] PWA service worker confirmed: ${serviceWorkerPath}`);
console.log(`[vps-build] PWA Workbox dependency confirmed: ${workboxPath}`);
console.log(`[vps-build] Push worker confirmed: ${pushWorkerPath}`);
